version: "3"

services:
  api:
    image: dotnet-webapi/api:${VERSION}
    container_name: dotnet-api-dev
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5000:5000
    volumes:
      - ./src/.:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: pg-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - dotnet-pg:/var/lib/postgresql/data

volumes:
  dotnet-pg:
